# ... existing services ...
  chat:
    image: iamtsm/tl-rtc-file:latest
    container_name: chat-service
    ports:
      - "9092:9092"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network
# ... existing code ... 