// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtgavzebubhzlcnzxuet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Z2F2emVidWJoemxjbnp4dWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzUyMDcsImV4cCI6MjA2NTUxMTIwN30.jzIuIeXoaqtN6myewiSsPLt86NaUWYYk16CaCFacqk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);